### PR TITLE
Fix overflow in bound checks

### LINKED ISSUE #140: Segmentation Faults in MMDB_open()
Hello,
I was using American Fuzzy Lop (afl-fuzz) to fuzz input to a modified version of `open.cpp` test program. Is fixing these crashes something you're interested in? The input files and a copy of the `open.cpp` can be found here: https://github.com/rwhitworth/libmaxminddb-fuzz.

The files can be executed as `./open id_filename` to cause seg faults.

Let me know if I can provide any more information to help narrow down this issue.

### PR DESCRIPTION
**Pull request by oschwald**
A corrupt database could cause a segmentation fault if it had a data
pointer large enough to cause an overflow in the existing bound checks.

Fixes #140.

### CODE REVIEW

File: src/maxminddb.c [hunk 1]
```diff
@@ -1384,7 +1384,10 @@ LOCAL int decode_one(MMDB_s *mmdb, uint32_t offset,
 {
     const uint8_t *mem = mmdb->data_section;
 
-    if (offset + 1 > mmdb->data_section_size) {
+    // We subtract rather than add as it possible that offset + 1
+    // could overflow for a corrupt database while an underflow
+    // from data_section_size - 1 should not be possible.
+    if (offset > mmdb->data_section_size - 1) {
```
Comment (horgh) [inline src/maxminddb.c]: I wonder if we should add a check that `data_section_size` is not zero (possibly where we initialize it) causing the `- 1` to wrap around? It sounds like it should never be the case, but a check could give more confidence.

I see you do checks that the `data_section_size` is not too small in a few places in this changeset. Maybe we should do that in all of them? Possibly there is a minimum already enforced somewhere that I missed.

Comment (oschwald) [inline src/maxminddb.c]: I don't think it is possible to construct such a database as the metadata will be more than three bytes. I did the additional check on values that could be significantly larger based on their construction. However, I am not opposed to adding a check when we open the database.

File: dev-bin/regen-prototypes.pl [hunk 2]
```diff
@@ -90,7 +90,7 @@ sub _regen_prototypes {
 
 my $return_type_re = qr/(?:\w+\s+)+?\**?/;
 my $signature_re   = qr/\([^\(\)]+?\)/;
-my $c_function_re  = qr/($return_type_re(\w+)$signature_re)(?>\n{)/s;
+my $c_function_re  = qr/($return_type_re(\w+)$signature_re)(?>\n\{)/s;
```
Comment (oschwald) [inline dev-bin/regen-prototypes.pl]: Good catch. I didn't even look to see if it was used.
