### PR TITLE
Fix overflow in search_tree_size

### LINKED ISSUE #335: Python vs C extension difference with large db
We have a custom built db with the following details:

- record size: 32
- node count: 542155119
- file size: 4339498906

The database works with python implementation. The latest maxminddb python library came with a vendored copy of `libmaxminddb`, and we noticed that the database doesn't work with the C extension.

Opening the database succeeds, but a query for an IP results in

```
maxminddb.errors.InvalidDatabaseError: Error looking up 192.0.2.0. The MaxMind DB file's search tree is corrupt
```

Slightly smaller database works properly also with the C extension, so maybe the database size is the problem?

### PR DESCRIPTION
**Pull request by oschwald**
Also, add guards to follow-up calculations to error if they overflow.

Closes #335.

### CODE REVIEW

File: src/maxminddb.c [hunk 1]
```diff
@@ -289,18 +290,28 @@ int MMDB_open(const char *const filename, uint32_t flags, MMDB_s *const mmdb) {
...
     mmdb->data_section =
         mmdb->file_content + search_tree_size + MMDB_DATA_SECTION_SEPARATOR;
-    if (search_tree_size + MMDB_DATA_SECTION_SEPARATOR >
-        (uint32_t)mmdb->file_size) {
+    if (search_tree_size + MMDB_DATA_SECTION_SEPARATOR > mmdb->file_size) {
+        status = MMDB_INVALID_METADATA_ERROR;
+        goto cleanup;
+    }
+    ssize_t data_section_size =
+        mmdb->file_size - search_tree_size - MMDB_DATA_SECTION_SEPARATOR;
```
Comment (horgh) [inline src/maxminddb.c:309]: Would underflow be possible?

**Review by horgh — CHANGES_REQUESTED** [review]
Not sure we need to change anything, but a couple questions.

File: src/maxminddb.c (hunk 1 above)
Comment (oschwald) [reply src/maxminddb.c:309]: Isn't that what line 304 is checking?

Comment (horgh) [reply src/maxminddb.c:309]: Hmm, yeah it should cover it too I think, you're right.

File: src/maxminddb.c [hunk 2]
```diff
@@ -289,18 +290,28 @@ int MMDB_open(const char *const filename, uint32_t flags, MMDB_s *const mmdb) {
...
+        goto cleanup;
+    }
+    ssize_t search_tree_size = (ssize_t)mmdb->metadata.node_count *
+                               (ssize_t)mmdb->full_record_byte_size;
 
     mmdb->data_section =
         mmdb->file_content + search_tree_size + MMDB_DATA_SECTION_SEPARATOR;
-    if (search_tree_size + MMDB_DATA_SECTION_SEPARATOR >
-        (uint32_t)mmdb->file_size) {
+    if (search_tree_size + MMDB_DATA_SECTION_SEPARATOR > mmdb->file_size) {
```
[the remark this answers is not in the document]
Comment (oschwald) [reply src/maxminddb.c]: I am not sure how plausibly this is an issue, but I did add a check.  The first part of the updated check is likely redundant as finding the metadata would have failed if that is not true, but I left it for clarity.

**Review by horgh — APPROVED** [review]
