### PR TITLE
Fix Clang static analysis warnings

### LINKED ISSUE #86: Warnings when building
Building in Clang as part of a distinct package, rgeolocate, we get [these warnings](https://github.com/Ironholds/rgeolocate/issues/11). They appear to be in libmaxminddb; any idea?

### PR DESCRIPTION
**Pull request by oschwald**
https://www.pivotaltracker.com/story/show/98956228

Closes #86

### CODE REVIEW

File: src/maxminddb.c [hunk 1]
```diff
@@ -816,6 +823,8 @@ LOCAL record_info_s record_info_for_database(MMDB_s *mmdb)
         record_info.left_record_getter = &get_uint32;
         record_info.right_record_getter = &get_uint32;
         record_info.right_record_offset = 4;
+    } else {
+        assert(false);
```
Comment (oschwald) [inline src/maxminddb.c]: This is appropriate as an assert as we already checked that the record_size from the database was 24, 28, or 32. This should only happen if there was a programming error on our part.
